apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logquery-operator-cluster
rules:
  - apiGroups: ["logquery.k8swhi.com"]
    resources: ["logqueries"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logquery-operator-cluster-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: logquery-operator-cluster
  apiGroup: rbac.authorization.k8s.io
