apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logqueries.logquery.k8swhi.com
spec:
  group: logquery.k8swhi.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [podName, query]
              properties:
                podName:
                  type: string
                query:
                  type: string
            status:
              type: object
              properties:
                answer:
                  type: string
                phase:
                  type: string
  scope: Namespaced
  names:
    plural: logqueries
    singular: logquery
    kind: LogQuery
    shortNames:
      - lq
